### ISSUE TITLE
Make --explore mode do something sensible when it gets to a resource rather than a capability..

### ISSUE THREAD

**Issue by zimeon** [resync/resync#12]
sw272@sf-lib-web-004 ~/resync-arxiv-expt>resync --explore http://resync.library.cornell.edu
Will look for discovery information based on mappings

Reading http://resync.library.cornell.edu/.well-known/resourcesync
Parsed capabilitylistindex document with 6 entries:
[1] http://resync.library.cornell.edu/arxiv-all/capabilitylist.xml
  capability not specified, should be capabilitylist
[2] http://resync.library.cornell.edu/arxiv-cs/capabilitylist.xml
  capability not specified, should be capabilitylist
[3] http://resync.library.cornell.edu/arxiv-q-bio/capabilitylist.xml
  capability not specified, should be capabilitylist
[4] http://resync.library.cornell.edu/sim100/capabilitylist.xml
  capability not specified, should be capabilitylist
[5] http://resync.library.cornell.edu/sim1000/capabilitylist.xml
  capability not specified, should be capabilitylist
[6] http://resync.library.cornell.edu/sim10000/capabilitylist.xml
  capability not specified, should be capabilitylist
Follow [number or q(uit)]?4

Reading http://resync.library.cornell.edu/sim100/capabilitylist.xml
Parsed capabilitylist document with 2 entries:
[1] http://resync.library.cornell.edu/sim100/changelist.xml
  changelist
[2] http://resync.library.cornell.edu/sim100/resourcelist.xml
  resourcelist
Follow [number or q(uit)]?1

Reading http://resync.library.cornell.edu/sim100/changelist.xml
Parsed changelist document with 10 entries:
[1] http://resync.library.cornell.edu/sim100/resources/8
Traceback (most recent call last):
  File "/usr/bin/resync", line 343, in <module>
    main()
  File "/usr/bin/resync", line 311, in main
    c.explore()
  File "/usr/lib/python2.6/site-packages/resync/client.py", line 434, in explore
    (uri, acceptable_capabilities, inp) = self.explore_uri(uri,acceptable_capabilities)
  File "/usr/lib/python2.6/site-packages/resync/client.py", line 481, in explore_uri
    elif (len(entry_caps)==1):
UnboundLocalError: local variable 'entry_caps' referenced before assignment

**Comment by zimeon** [comment]
This is resolved in 1.0.5 (not sure which version fixed it), e.g:

```
> resync-explorer  http://resync.library.cornell.edu
----- ResourceSync Explorer -----
Using URI mapping: http://resync.library.cornell.edu -> resync.library.cornell.edu
Looking for discovery information based on mappings

Reading http://resync.library.cornell.edu/.well-known/resourcesync
Parsed description document with 3 entries:
WARNING - expected a capabilitylist,capabilitylistindex document
[d] rel='describedby' link to http://resync.library.cornell.edu/
[1] http://resync.library.cornell.edu/sim100/capabilitylist.xml
  capabilitylist
[2] http://resync.library.cornell.edu/sim1000/capabilitylist.xml
  capabilitylist
[3] http://resync.library.cornell.edu/sim10000/capabilitylist.xml
  capabilitylist
Follow [number, q(uit)]?1

Reading http://resync.library.cornell.edu/sim100/capabilitylist.xml
Parsed capabilitylist document with 2 entries:
[d] rel='describedby' link to http://resync.library.cornell.edu/sim100
[u] rel='up' link to http://resync.library.cornell.edu/.well-known/resourcesync
[1] http://resync.library.cornell.edu/sim100/resourcelist.xml
  resourcelist
[2] http://resync.library.cornell.edu/sim100/changelist.xml
  changelist
Follow [number, b(ack), q(uit)]?1

Reading http://resync.library.cornell.edu/sim100/resourcelist.xml
Parsed resourcelist document with 67 entries:
[d] rel='describedby' link to http://resync.library.cornell.edu/sim100
[u] rel='up' link to http://resync.library.cornell.edu/sim100/capabilitylist.xml
[1] http://resync.library.cornell.edu/sim100/resources/1300
[2] http://resync.library.cornell.edu/sim100/resources/1302
[3] http://resync.library.cornell.edu/sim100/resources/1262
[4] http://resync.library.cornell.edu/sim100/resources/1267
[5] http://resync.library.cornell.edu/sim100/resources/1306
[6] http://resync.library.cornell.edu/sim100/resources/1078
[7] http://resync.library.cornell.edu/sim100/resources/1370
[8] http://resync.library.cornell.edu/sim100/resources/1373
[9] http://resync.library.cornell.edu/sim100/resources/1372
[10] http://resync.library.cornell.edu/sim100/resources/1375
[11] http://resync.library.cornell.edu/sim100/resources/1374
[12] http://resync.library.cornell.edu/sim100/resources/1377
[13] http://resync.library.cornell.edu/sim100/resources/1376
[14] http://resync.library.cornell.edu/sim100/resources/1379
[15] http://resync.library.cornell.edu/sim100/resources/1378
[16] http://resync.library.cornell.edu/sim100/resources/1096
[17] http://resync.library.cornell.edu/sim100/resources/1314
[18] http://resync.library.cornell.edu/sim100/resources/1313
[19] http://resync.library.cornell.edu/sim100/resources/1311
[20] http://resync.library.cornell.edu/sim100/resources/1319
(not showing remaining 47 entries)
Follow [number, b(ack), q(uit)]?1

Reading http://resync.library.cornell.edu/sim100/resources/1300
HEAD http://resync.library.cornell.edu/sim100/resources/1300
  status: 405
Follow [b(ack), q(uit)]?b

Reading http://resync.library.cornell.edu/sim100/resourcelist.xml
Parsed resourcelist document with 66 entries:
[d] rel='describedby' link to http://resync.library.cornell.edu/sim100
[u] rel='up' link to http://resync.library.cornell.edu/sim100/capabilitylist.xml
[1] http://resync.library.cornell.edu/sim100/resources/1300
[2] http://resync.library.cornell.edu/sim100/resources/1302
[3] http://resync.library.cornell.edu/sim100/resources/1262
[4] http://resync.library.cornell.edu/sim100/resources/1267
[5] http://resync.library.cornell.edu/sim100/resources/1306
[6] http://resync.library.cornell.edu/sim100/resources/1078
[7] http://resync.library.cornell.edu/sim100/resources/1370
[8] http://resync.library.cornell.edu/sim100/resources/1373
[9] http://resync.library.cornell.edu/sim100/resources/1372
[10] http://resync.library.cornell.edu/sim100/resources/1375
[11] http://resync.library.cornell.edu/sim100/resources/1374
[12] http://resync.library.cornell.edu/sim100/resources/1377
[13] http://resync.library.cornell.edu/sim100/resources/1376
[14] http://resync.library.cornell.edu/sim100/resources/1378
[15] http://resync.library.cornell.edu/sim100/resources/1096
[16] http://resync.library.cornell.edu/sim100/resources/1314
[17] http://resync.library.cornell.edu/sim100/resources/1313
[18] http://resync.library.cornell.edu/sim100/resources/1311
[19] http://resync.library.cornell.edu/sim100/resources/1319
[20] http://resync.library.cornell.edu/sim100/resources/1061
(not showing remaining 46 entries)
Follow [number, b(ack), q(uit)]?2

Reading http://resync.library.cornell.edu/sim100/resources/1302
HEAD http://resync.library.cornell.edu/sim100/resources/1302
  status: 405
Follow [b(ack), q(uit)]?q

resync-explorer done, bye...

> resync-explorer --version
resync-explorer 1.0.5
```
