### ISSUE TITLE
Source URI -> path translation error

### ISSUE THREAD

**Issue by behas** [resync/resync#13]
When syncing with arxiv, I get the following error:

```
➜  resync git:(master) mkdir /tmp/mycopy
➜  resync git:(master) resync --noauth -v http://arxiv.resourcesync.net/arxiv-q-bio /tmp/mycopy
Reading sitemap http://arxiv.resourcesync.net/arxiv-q-bio/resourcelist.xml
Read source resource_list, 3981 resources listed
Status: NOT IN SYNC (same=0, to create=3981, to update=0, to delete=0)
Will GET 3981 resources
Traceback (most recent call last):
  File "/usr/local/bin/resync", line 343, in <module>
    main()
  File "/usr/local/bin/resync", line 303, in main
    audit_only=args.audit)
  File "/Library/Python/2.7/site-packages/resync/client.py", line 173, in baseline_or_audit
    file = self.mapper.src_to_dst(uri)
  File "/Library/Python/2.7/site-packages/resync/mapper.py", line 99, in src_to_dst
    raise MapperError("Unable to translate source URI (%s) into a destination path." % (src_uri))
resync.mapper.MapperError: Unable to translate source URI (http://resync.library.cornell.edu/arxiv/ftp/q-bio/papers/0309/0309001.abs) into a destination path.

'''
```

**Comment by zimeon** [comment]
Very old issue and I'm not sure whether it was addressed of how to test readily. There is no way to say that two hostnames should be treated as one and that seems a real edge case. There may be some changes from 2014 around `--noauth` and `--strictauth` flags. Closing
