### ISSUE TITLE
Fix tests in python 2.6

### ISSUE THREAD

**Issue by zimeon** [resync/resync#23]
Something is wrong with `coverage` run in python 2.6 that appears to be connected with problems reported in 4.3.2, 4.3.3, 4.3.3 - see https://coverage.readthedocs.io/en/coverage-4.3.4/changes.html . Going back and rerunning travis tests on commits that previously passed now shows them broken, so it doesn't seem to be a code change in `resync`

**Comment by zimeon** [comment]
The report from travis on 2.6 is:

```
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    'coverage': Coverage
  File "/opt/python/2.6.9/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/opt/python/2.6.9/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/opt/python/2.6.9/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/test.py", line 210, in run
    self.run_tests()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/test.py", line 231, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 816, in __init__
    self.parseArgs(argv)
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 843, in parseArgs
    self.createTests()
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 849, in createTests
    self.module)
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 613, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 587, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/opt/python/2.6.9/lib/python2.6/unittest.py", line 584, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_resource_list_multifile'
```

**Comment by zimeon** [comment]
This doesn't seem to be to do with coverage but instead perhaps a problem with setuptools. Anyhow, I'm going to abandon attempts to support python2.6 as it seems that the community is rapidly moving away from it now anyway.
